### ISSUE TITLE
ValueError: could not broadcast input array from shape (32,29) into shape (32,32)

### ISSUE THREAD

**Issue by parsibox** [ammoradi/farsi-car-number-plate-recognition#2]
```
python3.6 main.py 
Using TensorFlow backend.

(32, 32)
[2.]
(32, 32)
[0.]
(32, 32)
[0.]
(32, 32)
[0.]
(32, 32)
[0.]
(32, 32)
[0.]
(32, 32)
[0.]
(32, 32)
[0.]
(32, 29)
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    prediction = classifier.knn_classify(number)
  File "/home/mohsen/Desktop/python/farsi-car-number-plate-recognition/classifier.py", line 68, in knn_classify
    test_data[0] = img
ValueError: could not broadcast input array from shape (32,29) into shape (32,32)

```

**Comment by ammoradi** [comment]
@parsibox can I see a sample of your dataset?

**Comment by parsibox** [comment]
i do not change any thing
i run your sample code

**Comment by ammoradi** [comment]
@parsibox Ok. I will check this case and update repo if I made a mistake.

**Comment by parsibox** [comment]
![1](https://user-images.githubusercontent.com/12513476/59562875-7914e100-9047-11e9-9de3-c44222eeced0.jpg)
thi is my image
![image](https://user-images.githubusercontent.com/12513476/59562877-85993980-9047-11e9-9063-5199b3d65757.png)
![image](https://user-images.githubusercontent.com/12513476/59562879-8fbb3800-9047-11e9-8ab4-8790cdaebbef.png)
![image](https://user-images.githubusercontent.com/12513476/59562894-c09b6d00-9047-11e9-9548-1f29faede5f5.png)

**Comment by parsibox** [comment]
did you try it?

**Comment by ammoradi** [comment]
@parsibox i have not free time until next week.
* PRs welcome

**Comment by parsibox** [comment]
ok i wait for you

**Comment by ammoradi** [comment]
the bug is from the detector.
it should not detect the blue part of the flag but it does!
I will try to fix this.

**Comment by parsibox** [comment]
thanks
i need this code

**Comment by parsibox** [comment]
i am still waiting for you

**Comment by ammoradi** [comment]
@parsibox could you please upload your testing image somewhere and give me a download link?

**Comment by parsibox** [comment]
this is my image
https://user-images.githubusercontent.com/12513476/59562875-7914e100-9047-11e9-9de3-c44222eeced0.jpg

**Comment by parsibox** [comment]
https://srv-file4.gofile.io/download/JZ4cSa/1.jpg

**Comment by parsibox** [comment]
i am still waiting for you

**Comment by SabraHashemi** [comment]
> i am still waiting for you

did you solve this problem? i had same problem

**Comment by parsibox** [comment]
no

**Comment by SabraHashemi** [comment]
> no

i think we can rewrite this resize function
tarfget is to resize any image to 32*32

**Comment by SabraHashemi** [comment]
def __resize_image(src_image, dst_image_height, dst_image_width):
    src_image_height = src_image.shape[0]
    src_image_width = src_image.shape[1]

    if src_image_height > dst_image_height or src_image_width > dst_image_width:
        height_scale = dst_image_height / src_image_height
        width_scale = dst_image_width / src_image_width
        scale = min(height_scale, width_scale)
        img = cv2.resize(src=src_image, dsize=(0, 0), fx=scale, fy=scale, interpolation=cv2.INTER_CUBIC)
    else:
        img = src_image

    img_height = img.shape[0]
    img_width = img.shape[1]

    dst_image = np.zeros(shape=[dst_image_height, dst_image_width], dtype=np.uint8)

    y_offset = (dst_image_height - img_height) // 2
    x_offset = (dst_image_width - img_width) // 2

    dst_image[y_offset:y_offset+img_height, x_offset:x_offset+img_width] = img

    return dst_image

**Comment by ammoradi** [comment]
@parsibox @sabrabano0 I was far from this subject for years. let me read the principles used in this project and try to fix this bug.
maybe I should refactor or rebase this project. because it is not funny to deal with this problem with `knn` or a simple `cnn` it should be under sth like `YOLO` or `SSD` hand!

**Comment by SabraHashemi** [comment]
> @parsibox @sabrabano0 I was far from this subject for years. let me read the principles used in this project and try to fix this bug.
> maybe I should refactor or rebase this project. because it is not funny to deal with this problem with `knn` or a simple `cnn` it should be under sth like `YOLO` or `SSD` hand!



Not so complicated, as I mentioned above the problem  is in the function resize. You have included resizing for bigger  image than 32 x 32 but not for smaller like  24 x 32.
